### ISSUE TITLE
建议加入搜狗搜索适配

### ISSUE THREAD

**Issue by Sev73n** [h2y/sotab#2]
百度近期事件就不说了
搜索加入了搜狗英文（据说是来自谷歌？）
还有搜狗名医 引擎能力有明显提高
同时之前搜狗会降低百度结果的排名
近期百度事件之后 对百度的筛选有了新的算法
一些合理的贴吧和知道的结果也靠前了
相比较百度无耻的排名极致和推广自家产品的做法

搜狗能够正常搜索到百度的精华结果（知道 贴吧等）
还有知乎和微信的结果
是一个国内很好的搜索替代 希望作者能适配到您的插件中

祝好运!

**Comment by h2y** [comment]
感谢你的反馈，现在已适配搜狗引擎。
支持搜狗的多个搜索模式的跳转以及转入。

**Comment by h2y** [comment]
但现在的问题是在搜狗的知乎搜索页面，无法弹出 soTab 搜索切换框，原因不明，等有时间了在研究。

<http://zhihu.sogou.com/zhihu?query=%E8%83%A1%E4%B8%AD%E5%85%83>

**Comment by Sev73n** [comment]
提的两个问题都积极解决了 开发者真棒！
