### ISSUE TITLE
ALLSO 无法打开？

### ISSUE THREAD

**Issue by dpast** [h2y/sotab#4]
<img width="1279" alt="2016-06-02 09 30 59" src="https://cloud.githubusercontent.com/assets/9845703/15731066/ce5bdbb8-28a4-11e6-8117-baad7c8ed2dd.png">

**Comment by h2y** [comment]
我这里测试并没有该问题。
看截图是由于 css 由于网络原因没有正确加载，一般来说按 `ctrl+f5` 强制刷新缓存即可解决。

**Comment by dpast** [comment]
还是不行。全局代理也不行。也许是无法再现的个人原因...
**2016-06-02 09 30 59**
<img width="1279" alt="2016-06-02 09 30 59" src="https://cloud.githubusercontent.com/assets/9845703/15781688/dbae6e44-29d9-11e6-900d-c107c4cc59e6.png">
**2016-06-03 19 54 13**
<img width="1280" alt="2016-06-03 19 54 13" src="https://cloud.githubusercontent.com/assets/9845703/15781695/e7b3025e-29d9-11e6-9527-75d554a8457e.png">
