### ISSUE TITLE
新样式会遮挡搜索内容 建议微调

### ISSUE THREAD

**Issue by Sev73n** [h2y/sotab#5]
![Uploading BaiduShurufa_2016-6-5_16-38-31.png…]()

上周更新的版本调整了样式改成了半圆形
更加醒目 便于寻找 但是也有遮挡内容的问题
可以适当微调

最好是能缩小后贴边 进露出细长条斜着ALLSO 然后半透明状态

鼠标放上去再显示不透明的跨引擎搜索条

**Comment by h2y** [comment]
谢谢反馈，已更新。

在所有引擎中，现在缩小后的位置更靠外。
